short_ny/routes.py
from flask import Blueprint, flash, render_template, url_for, request, redirect
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import current_user, login_user, logout_user, login_required
from .extensions import db, cache, limiter
from .models import  Link
import random, string, requests, io, qrcode


shortner = Blueprint('shortner', __name__)



def generate_short_link(length=5):
    chars = string.ascii_letters + string.digits
    short_link = ''.join(random.choice(chars) for _ in range(length))
    return short_link


def generate_qr_code(link):
    image = qrcode.make(link)
    image_io = io.BytesIO()
    image.save(image_io, 'PNG')
    image_io.seek(0)
    return image_io


@shortner.errorhandler(404)
def error_404(error):
    return render_template('404.html'), 404


@shortner.errorhandler(403)
def error_404(error):
    return render_template('403.html'), 403


@shortner.route('/', methods=['GET', 'POST'])
@limiter.limit('10/minutes')
def index():
    if request.method == 'POST':
        long_link = request.form['long_link']
        custom_path = request.form['custom_path'] or None
        long_link_exists = Link.query.filter_by(user_id=current_user.id).filter_by(long_link=long_link).first()

        if requests.get(long_link).status_code != 200:
            return render_template('404.html')

        elif long_link_exists:
            flash ('This link has already been shortened.')
            return redirect(url_for('shortner.dashboard'))

        elif custom_path:
            path_exists = Link.query.filter_by(custom_path=custom_path).first()
            if path_exists:
                flash ('That custom path is taken. Please try another.')
                return redirect(url_for('shortner.index'))
            short_link = custom_path

        elif long_link[:4] != 'http':
            long_link = 'http://' + long_link
        
        else:
            while True:
                short_link = generate_short_link()
                short_link_exists = Link.query.filter_by(short_link=short_link).first()
                if not short_link_exists:
                    break
        
        link = Link(long_link=long_link, short_link=short_link, custom_path=custom_path, user_id=current_user.id)
        db.session.add(link)
        db.session.commit()
        return redirect(url_for('shortner.dashboard'))
    
    return render_template('index.html')


@shortner.route('/about')
def about():
    return render_template('about.html')


@shortner.route('/dashboard')
@login_required
def dashboard():
    links = Link.query.filter_by(user_id=current_user.id).order_by(Link.created_at.desc()).all()
    host = request.host_url
    return render_template('dashboard.html', links=links, host=host)


@shortner.route('/history')
@login_required
def history():
    links = Link.query.filter_by(user_id=current_user.id).order_by(Link.created_at.desc()).all()
    host = request.host_url
    return render_template('history.html', links=links, host=host)


@shortner.route('/<short_link>')
@cache.cached(timeout=30)
def redirect_link(short_link):
    link = Link.query.filter_by(short_link=short_link).first()
    if link:
        link.clicks += 1
        db.session.commit()
        return redirect(link.long_link)
    else:
        return render_template('404.html')


@shortner.route('/<short_link>/qr_code')
@login_required
@cache.cached(timeout=30)
@limiter.limit('10/minutes')
def generate_qr_code_link(short_link):
    link = Link.query.filter_by(user_id=current_user.id).filter_by(short_link=short_link).first()

    if link:
        image_io = generate_qr_code(request.host_url + link.short_link)
        return image_io.getvalue(), 200, {'Content-Type': 'image/png'}
    
    return render_template('404.html')


@shortner.route('/<short_link>/delete')
@login_required
def delete(short_link):
    link = Link.query.filter_by(user_id=current_user.id).filter_by(short_link=short_link).first()

    if link:
        db.session.delete(link)
        db.session.commit()
        return redirect(url_for('shortner.dashboard'))
    
    return render_template('404.html')


@shortner.route('/<short_link>/edit', methods=['GET', 'POST'])
@login_required
@limiter.limit('10/minutes')
def update(short_link):
    link = Link.query.filter_by(user_id=current_user.id).filter_by(short_link=short_link).first()
    host = request.host_url
    if link:
        if request.method == 'POST':
            custom_path = request.form['custom_path']
            if custom_path:
                link_exists = Link.query.filter_by(custom_path=custom_path).first()
                if link_exists:
                    flash ('That custom path already exists. Please try another.')
                    return redirect(url_for('shortner.update', short_link=short_link))
                link.custom_path = custom_path
                link.short_link = custom_path
            db.session.commit()
            return redirect(url_for('shortner.dashboard'))
        return render_template('edit.html', link=link, host=host)
    return render_template('404.html')


@shortner.route('/<short_link>/analytics')
@login_required
def analytics(short_link):
    link = Link.query.filter_by(user_id=current_user.id).filter_by(short_link=short_link).first()
    host = request.host_url
    if link:
        return render_template('analytics.html', link=link, host=host)
    return render_template('404.html')

short_ny/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock title %}

{% block content %}
<section class="container">
  {% if current_user.is_authenticated %}
  <h2>Welcome to Scissor, {{ current_user.username }}! <span class="wave">👋🏾</span></h2>
  {% else %}
  <h2>Welcome to Scissor! <span class="wave">👋🏾</span></h2>
  {% endif %}
    
  <h3>"Brief is the new Black"</h3>
  
  <p>This is what inspires the team at Scissor</p>
    
  <p>In today's world, it's important to keep things brief</p> 
    
  <p>Scissor is a simple tool which makes URLs as short as possible</p>

  <p>Scissor converts long URLs into easily sharable QR codes and short, customizable links</p>
</section>
{% endblock content %}

short_ny/templates/analytics.html
{% extends 'base.html' %}
{% block title %}Link Analytics{% endblock title %}
{% block content %}
{% if current_user.is_authenticated %}
  {% if link %}
    <section class="container analytics-container">
      <div class="card analytics-card">
        <div class="card-body">
          <img class="card-qrcode" src="{{ url_for('shortner.generate_qr_code_link', short_link=link.short_link) }}" alt="QR Code">
          <br>
          <a href="{{ url_for('shortner.generate_qr_code_link', short_link=link.short_link) }}" download="qrcode image">
            <button class="button">Download QR Code</button>
          </a>
          <hr>
          <small>
            Created: {{link.created_at.strftime('%B %d, %Y')}} || Clicks: {{link.clicks}}
          </small>
          <p>
            Original Link: <br>
            <a href="{{link.long_link}}" target="_blank">{{link.long_link}}</a>
          </p>
          <p>
            Shortened Link: <br>
            <a href="{{url_for('shortner.redirect_link', short_link=link.short_link)}}" target="_blank">{{host}}{{link.short_link}}</a>
          </p>
          <a href="{{ url_for('shortner.update', short_link=link.short_link) }}">
            <button class="button">Edit Link</button>
          </a>
          <a href="{{ url_for('shortner.delete', short_link=link.short_link) }}">
            <button class="button">Delete Link</button>
          </a>
        </div>
      </div>
  {% else %}
    <small>
      This link does not exist (yet). <a href="{{url_for('shortner.index')}}">Create One</a>
    </small>
  {% endif %}
{% else %}
  <small>
    <a href="{{url_for('auth.login')}}">Log in</a> to see link stats
  </small>
{% endif %}
{% endblock content %}

short_ny/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{url_for('static',filename= 'css/main.css')}}"
    />
    <title>{% block title %}{% endblock title %} - Scissor</title>
  </head>
  <body>
    <header>
      <div class="logo-container">
        <a href="{{url_for('shortner.index')}}">
          <img
            src="{{url_for('static',filename= 'scissor-logo/default.png')}}"
            alt="Logo"
            width="100"
            height="60"
            class="header-logo"
          />
        </a>
      </div>
      <div class="nav-bar">
        <a href="{{url_for('shortner.index')}}">Home</a>
        <a href="{{url_for('shortner.about')}}">About</a>
        {% if current_user.is_authenticated %}
        <a href="{{url_for('shortner.dashboard')}}">Dashboard</a>
        <a href="{{url_for('shortner.history')}}">History</a>
        <a href="{{url_for('auth.logout')}}">Log Out</a>
        {% else %}
        <a href="{{url_for('auth.register')}}">Sign Up</a>
        <a href="{{url_for('auth.login')}}">Log In</a>
        {% endif %}
      </div>
    </header>
    {% with messages = get_flashed_messages() %} {% if messages %}
    <div class="container">
      {% for message in messages %}
      <p>{{ message }} <a href="{{request.path}}">Dismiss</a></p>
      {% endfor %}
    </div>
    {% endif %} {% endwith %}
    <main>{% block content %}{% endblock content %}</main>
    <footer class="container">
      <p class="footer">
        <a href="https://twitter.com/Zichdan_" class="twitter" target="_blank"
          >@Zichdan</a
        >,
        <a href="https://altschoolafrica.com/schools/engineering" target="_blank"
          >AltSchool Africa</a
        >
        <script>
          document.write(new Date().getFullYear());
        </script>
      </p>
    </footer>
  </body>
</html>

short_ny/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
{% if current_user.is_authenticated %}
  {% if links %}
    <section class="dashboard">
      {% for link in links %}
        <div class="card">
          <div class="card-body">
            <img class="card-qrcode" src="{{ url_for('shortner.generate_qr_code_link', short_link=link.short_link) }}" alt="QR Code">
            <br>
            <a href="{{ url_for('shortner.generate_qr_code_link', short_link=link.short_link) }}" download="qrcode image">
              <button class="button">Download QR Code</button>
            </a>
            <hr>
            <small>
              Created: {{link.created_at.strftime('%B %d, %Y')}} || Clicks: {{link.clicks}}
            </small>
            <p>
              Original Link: <br>
              <a href="{{link.long_link}}" target="_blank">{{link.long_link}}</a>
            </p>
            <p>
              Shortened Link: <br>
              <a href="{{url_for('shortner.redirect_link', short_link=link.short_link)}}" target="_blank">{{host}}{{link.short_link}}</a>
            </p>
            <a href="{{ url_for('shortner.update', short_link=link.short_link) }}">
              <button class="button">Edit Link</button>
            </a>
            <a href="{{ url_for('shortner.delete', short_link=link.short_link) }}">
              <button class="button">Delete Link</button>
            </a>
          </div>
        </div>
      {% endfor %}
    </section>
  {% else %}
    <small>
      You do not have any links yet. <a href="{{url_for('shortner.index')}}">Create Some</a>
    </small>
  {% endif %}
{% else %}
  <small>
    <a href="{{url_for('shortner.login')}}">Log in</a> to see your links
  </small>
{% endif %}
{% endblock content %}

short_ny/templates/edit.html
{% extends 'base.html' %}
{% block title %}Edit Link{% endblock title %}
{% block content %}
<form action="{{url_for('shortner.update', short_link=link.short_link)}}" method="POST" class="form-container">
  <div class="form-group">
    <h3>Edit Link</h3>
  </div>
  <div class="form-group">
    <label for="long_link">Original Link</label>
    <input type="text" name="long_link" class="form-control" value="{{link.long_link}}" disabled/>
  </div>
  <div class="form-group">
    <label for="short_link">Old Shortened Link</label>
    <input type="text" name="short_link" class="form-control" value="{{host}}{{link.short_link}}" disabled/>
  </div>
  <div class="form-group">
    <label for="custom_path">New Back-Half</label>
    <input type="text" class="form-control" placeholder="{{link.short_link}}" name="custom_path" required/>
  </div>
  <div class="form-group">
    <input type="submit" value="Update Link" class="button"/>
  </div>
</form>
{% endblock content %}

short_ny/templates/history.html
{% extends 'base.html' %}
{% block title %}Link History{% endblock title %}
{% block content %}
<section class="container">
{% if links %}
<div class="table-wrapper">
  <table>
    <thead>
        <tr>
          <th>Short Link</th>
          <th>Original Link</th>
          <th>Analytics</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
    </thead>
    <tbody>
      {% for link in links %}
        <tr>
          <td><a href="{{ url_for('shortner.redirect_link', short_link=link.short_link) }}" target="_blank">{{host}}{{link.short_link}}</a></td>
          <td><a href="{{ link.long_link }}" target="_blank">{{link.long_link}}</a></td>
          <td><a href="{{ url_for('shortner.analytics', short_link=link.short_link) }}">Analytics</a></td>
          <td><a href="{{ url_for('shortner.update', short_link=link.short_link) }}">Edit</a></td>
          <td><a href="{{ url_for('shortner.delete', short_link=link.short_link) }}">Delete</a></td>
	      </tr>
	    {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<small>You do not have any links yet. <a href="{{url_for('shortner.index')}}">Create Some</a> </small>
{% endif %}
</section>
{% endblock content %}

short_ny/templates/index.html
{% extends 'base.html' %}
{% block title %}Link Shortener{% endblock title %}
{% block content %}
{% if current_user.is_authenticated %}
<h2>Welcome, {{ current_user.username }}! <span class="wave">👋🏾</span></h2>
<br>
<form action="{{url_for('shortner.index')}}" method="POST" class="form-container">
  <div class="form-group">
    <label for="long_link">Original Link</label>
    <input type="url" name="long_link" class="form-control" placeholder="https://example.com/long-link" required>
  </div>
  <div class="form-group">
    <label for="custom_path">Custom Back-Half (Optional)</label>
    <input type="text" name="custom_path" class="form-control" placeholder="Example: sciz.site/custom-back-half">
  </div>
  <div class="form-group">
    <input type="submit" value="Shorten Link" class="button"/>
  </div>
</form>
{% else %}
<div class="logo-container">
  <img
    src="{{url_for('static',filename= 'scissor-logo/vector/default-monochrome.svg')}}"
    alt="Logo"
    width="50%"
    class="logo"
  />
</div>
<h3>...brief is the new black</h3>
<small>
  <a href="{{url_for('auth.register')}}">Sign up</a> or <a href="{{url_for('auth.login')}}">log in</a> to shorten links for free
</small>
{% endif %}
{% endblock content %}

short_ny/templates/login.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock title %}

{% block content %}
<form action="{{url_for('auth.login')}}" method="POST" class="form-container">
  <div class="form-group">
    <h3>Log In</h3>
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" name="email" class="form-control"/>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control"/>
  </div>
  <div class="form-group">
    <input type="submit" value="Log In" class="button"/>
  </div>
</form>
<br />
<small>
  Don't have an account? <a href="{{url_for('auth.register')}}">Create One</a>
</small>
</div>
{% endblock content %}

short_ny/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock title %}
{% block content %}
<form action="{{url_for('auth.register')}}" method="POST" class="form-container">
  <div class="form-group">
    <h3>Create an Account</h3>
  </div>
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" name="username" class="form-control" required/>
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" name="email" class="form-control" required/>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control" required/>
  </div>
  <div class="form-group">
    <input type="submit" value="Sign Up" class="button"/>
  </div>
</form>
<br />
<small>
  Already have an account? <a href="{{url_for('auth.login')}}">Log In</a>
</small>
</div>
{% endblock content %}